sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info
  - node --version
  - npm --version

script:
  - cd alma-server/src/main/resources
  - pwd
  - npm install -g gulp
  - npm install
  - gulp minify
  - cd ../../../../
  - mvn clean verify -f alma-server/pom.xml -e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker images
  - docker push siestesa/alma-server:latest

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $TOKEN
  name : Build Travis $(date + '%d.%m.%Y %R')
  on:
    repo: siestsa/alma-m2-2017